import type { Report } from '@/lib/types';

function confidenceLabel(c: Report['confidence']): string {
  return c === 'high' ? 'High' : c === 'low' ? 'Low' : 'Medium';
}

export interface MarkdownOptions {
  /** Keep inline [n] markers (default) or strip them. */
  citations?: boolean;
  /** Include the metadata header block. */
  header?: boolean;
  now?: Date;
}

/** Render the report as portable Markdown (used for copy + .md download). */
export function reportToMarkdown(report: Report, opts: MarkdownOptions = {}): string {
  const citations = opts.citations !== false;
  const strip = (t: string) => (citations ? t : t.replace(/\s*\[\d+\]/g, '').replace(/ {2,}/g, ' ').trim());
  const lines: string[] = [];

  if (opts.header !== false) {
    lines.push(`# ${strip(report.title)}`);
    lines.push('');
    lines.push(`> **Question:** ${report.question}`);
    lines.push(
      `> **Confidence:** ${confidenceLabel(report.confidence)} — ${strip(report.confidenceReason)}`,
    );
    lines.push(`> **Generated:** ${new Date(report.generatedAt).toUTCString()}`);
    if (report.methodology) lines.push(`> **Method:** ${report.methodology}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('## Short answer');
  lines.push('');
  lines.push(strip(report.shortAnswer));
  lines.push('');

  if (report.findings.length) {
    lines.push('## Key findings');
    lines.push('');
    for (const f of report.findings) {
      lines.push(`### ${strip(f.heading)}`);
      lines.push('');
      for (const b of f.bullets) lines.push(`- ${strip(b)}`);
      lines.push('');
    }
  }

  const conflicts = report.conflicts ?? [];
  const uncertainties = report.uncertainties ?? [];
  if (conflicts.length || uncertainties.length) {
    lines.push('## Conflicts and uncertainty');
    lines.push('');
    for (const c of conflicts) lines.push(`- **Conflict:** ${strip(c)}`);
    for (const u of uncertainties) lines.push(`- ${strip(u)}`);
    lines.push('');
  }

  if (report.sources.length) {
    lines.push('## Sources');
    lines.push('');
    for (const s of report.sources) {
      const bits = [`${s.n}. **[${s.title}](${s.url})**`];
      const meta: string[] = [];
      if (s.domain) meta.push(s.domain);
      if (s.date) meta.push(s.date);
      if (s.type) meta.push(s.type);
      if (meta.length) bits.push(` — ${meta.join(' · ')}`);
      lines.push(bits.join(''));
      if (s.supports) lines.push(`   - Supports: ${strip(s.supports)}`);
      if (s.quote) lines.push(`   - Quote: “${strip(s.quote)}”`);
    }
    lines.push('');
  }

  if (report.integrityNotes?.length) {
    lines.push('## Integrity checks');
    lines.push('');
    for (const n of report.integrityNotes) lines.push(`- ${n}`);
    lines.push('');
  }

  if (report.followUpQuestions?.length) {
    lines.push('## Suggested follow-ups');
    lines.push('');
    for (const q of report.followUpQuestions) lines.push(`- ${q}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '_Generated by Deep Research Agent. Web content is treated as untrusted data; every citation points to a page the agent actually retrieved. Verify anything important before acting on it._',
  );
  return `${lines.join('\n').trim()}\n`;
}

/** Plain-text version for the clipboard. */
export function reportToPlainText(report: Report): string {
  return reportToMarkdown(report)
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\[(.+?)\]\((.+?)\)/g, '$1 ($2)')
    .replace(/^>\s?/gm, '')
    .replace(/^---$/gm, '────────');
}

/** Everything a user might want when copying a single section. */
export function sourcesToMarkdown(report: Report): string {
  return report.sources
    .map((s) => `${s.n}. ${s.title} — ${s.url}${s.date ? ` (${s.date})` : ''}`)
    .join('\n');
}
