import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import type { Report } from '@/lib/types';
import { AppError } from '@/lib/errors';

/**
 * Server-side PDF rendering with pdf-lib's built-in Helvetica.
 * Those fonts only cover WinAnsi (Latin-1 + a few symbols), so text outside
 * that range is replaced and, if too much would be lost, we refuse and tell
 * the user to use Markdown / print-to-PDF instead.
 */

const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;
const MARGIN = 54;
const CONTENT_W = PAGE_W - MARGIN * 2;

const ENCODABLE =
  /[\u0009\u000a\u000d\u0020-\u007e\u00a0-\u00ff\u0152\u0153\u0160\u0161\u0178\u017d\u017e\u0192\u02c6\u02dc\u2013\u2014\u2018\u2019\u201a\u201c\u201d\u201e\u2020\u2021\u2022\u2026\u2030\u2039\u203a\u20ac\u2122]/;

export function sanitizeForPdf(text: string): string {
  let out = '';
  for (const ch of text.replace(/\r\n?/g, '\n')) {
    out += ENCODABLE.test(ch) ? ch : '?';
  }
  return out;
}

export function latinRatio(text: string): number {
  if (!text.length) return 1;
  let ok = 0;
  for (const ch of text) if (ENCODABLE.test(ch) || ch === ' ') ok++;
  return ok / [...text].length;
}

interface Ctx {
  doc: PDFDocument;
  page: PDFPage;
  font: PDFFont;
  bold: PDFFont;
  y: number;
  pageIndex: number;
}

class Pdf {
  private doc!: PDFDocument;
  private font!: PDFFont;
  private bold!: PDFFont;
  private italic!: PDFFont;
  private page!: PDFPage;
  private y = 0;
  private pageIndex = 0;

  async build(report: Report): Promise<Uint8Array> {
    this.doc = await PDFDocument.create();
    this.font = await this.doc.embedFont(StandardFonts.Helvetica);
    this.bold = await this.doc.embedFont(StandardFonts.HelveticaBold);
    this.italic = await this.doc.embedFont(StandardFonts.HelveticaOblique);
    this.doc.setTitle(sanitizeForPdf(report.title));
    this.doc.setSubject(sanitizeForPdf(report.question).slice(0, 300));
    this.doc.setProducer('Deep Research Agent');
    this.doc.setCreator('Deep Research Agent');
    this.newPage();

    this.heading(sanitizeForPdf(report.title), 19);
    this.paragraph(`Question: ${report.question}`, { size: 10, color: gray(0.35), italic: true });
    this.paragraph(
      `Confidence: ${report.confidence.toUpperCase()} — ${report.confidenceReason}`,
      { size: 10, color: gray(0.35) },
    );
    this.paragraph(
      `Generated ${new Date(report.generatedAt).toUTCString()}${report.methodology ? ` · ${report.methodology}` : ''}`,
      { size: 9, color: gray(0.5) },
    );
    this.rule();

    this.heading('Short answer', 13);
    this.paragraph(report.shortAnswer, { size: 11, lineHeight: 15.5 });

    if (report.findings.length) {
      this.heading('Key findings', 13);
      for (const f of report.findings) {
        this.heading(sanitizeForPdf(f.heading), 11.5, gray(0.2));
        for (const b of f.bullets) this.bullet(b);
        this.space(6);
      }
    }

    const conflicts = report.conflicts ?? [];
    const uncertainties = report.uncertainties ?? [];
    if (conflicts.length || uncertainties.length) {
      this.heading('Conflicts and uncertainty', 13);
      for (const c of conflicts) this.bullet(`Conflict: ${c}`);
      for (const u of uncertainties) this.bullet(u);
      this.space(6);
    }

    if (report.sources.length) {
      this.heading('Sources', 13);
      for (const s of report.sources) {
        this.paragraph(`[${s.n}] ${s.title}`, { size: 10.5, bold: true, spaceAfter: 2 });
        this.paragraph(`${s.url}${s.date ? ` · ${s.date}` : ''}${s.type ? ` · ${s.type}` : ''}`, {
          size: 9,
          color: gray(0.45),
          spaceAfter: 2,
        });
        if (s.supports) this.paragraph(`Supports: ${s.supports}`, { size: 9.5, indent: 12, color: gray(0.3) });
        if (s.quote) this.paragraph(`Quote: "${s.quote}"`, { size: 9.5, indent: 12, italic: true, color: gray(0.3) });
        this.space(4);
      }
      this.space(4);
    }

    if (report.integrityNotes?.length) {
      this.heading('Integrity checks', 13);
      for (const n of report.integrityNotes) this.bullet(n, { size: 9.5, color: gray(0.3) });
      this.space(6);
    }

    if (report.followUpQuestions?.length) {
      this.heading('Suggested follow-ups', 13);
      for (const q of report.followUpQuestions) this.bullet(q);
    }

    this.paragraph(
      'Generated by Deep Research Agent. Web content is treated as untrusted data and every citation points to a page the agent actually retrieved. Verify anything important before acting on it.',
      { size: 8.5, color: gray(0.5), spaceAfter: 0 },
    );

    this.stampFooters();
    return this.doc.save();
  }

  private newPage() {
    this.page = this.doc.addPage([PAGE_W, PAGE_H]);
    this.pageIndex += 1;
    this.y = PAGE_H - MARGIN;
  }

  private ensure(space: number) {
    if (this.y - space < MARGIN + 18) this.newPage();
  }

  private heading(text: string, size: number, color = rgb(0.06, 0.09, 0.16)) {
    this.ensure(size * 2.4);
    this.y -= size * 0.6;
    this.drawWrapped(text, { size, font: this.bold, color, lineHeight: size * 1.35 });
    this.y -= size * 0.35;
  }

  private paragraph(
    text: string,
    opts: { size?: number; lineHeight?: number; color?: any; bold?: boolean; italic?: boolean; indent?: number; spaceAfter?: number } = {},
  ) {
    const size = opts.size ?? 10.5;
    const lineHeight = opts.lineHeight ?? size * 1.42;
    const font = opts.bold ? this.bold : opts.italic ? this.italic : this.font;
    this.drawWrapped(sanitizeForPdf(text), {
      size,
      lineHeight,
      font,
      color: opts.color ?? rgb(0.13, 0.15, 0.2),
      indent: opts.indent ?? 0,
    });
    this.y -= opts.spaceAfter ?? 6;
  }

  private bullet(text: string, opts: { size?: number; color?: any } = {}) {
    const size = opts.size ?? 10.5;
    this.ensure(size * 1.8);
    this.page.drawText('-', { x: MARGIN + 4, y: this.y - size, size, font: this.font, color: opts.color ?? rgb(0.3, 0.32, 0.38) });
    this.drawWrapped(sanitizeForPdf(text), {
      size,
      lineHeight: size * 1.42,
      font: this.font,
      color: opts.color ?? rgb(0.13, 0.15, 0.2),
      indent: 14,
    });
    this.y -= 3;
  }

  private space(amount: number) {
    this.y -= amount;
  }

  private rule() {
    this.ensure(14);
    this.page.drawLine({
      start: { x: MARGIN, y: this.y },
      end: { x: PAGE_W - MARGIN, y: this.y },
      thickness: 0.6,
      color: rgb(0.82, 0.84, 0.88),
    });
    this.y -= 14;
  }

  private drawWrapped(
    text: string,
    opts: { size: number; lineHeight: number; font: PDFFont; color: any; indent?: number },
  ) {
    const indent = opts.indent ?? 0;
    const maxWidth = CONTENT_W - indent;
    const paragraphs = text.split('\n');
    for (const para of paragraphs) {
      const words = para.split(/\s+/).filter((w) => w.length > 0);
      if (!words.length) {
        this.y -= opts.lineHeight * 0.6;
        continue;
      }
      let line = '';
      for (const word of words) {
        const candidate = line ? `${line} ${word}` : word;
        if (opts.font.widthOfTextAtSize(candidate, opts.size) <= maxWidth) {
          line = candidate;
          continue;
        }
        if (line) this.flushLine(line, opts, indent);
        if (opts.font.widthOfTextAtSize(word, opts.size) > maxWidth) {
          // hard-split very long tokens (URLs, hashes)
          let chunk = '';
          for (const ch of word) {
            if (opts.font.widthOfTextAtSize(chunk + ch, opts.size) > maxWidth) {
              this.flushLine(chunk, opts, indent);
              chunk = ch;
            } else {
              chunk += ch;
            }
          }
          line = chunk;
        } else {
          line = word;
        }
      }
      if (line) this.flushLine(line, opts, indent);
    }
  }

  private flushLine(
    line: string,
    opts: { size: number; lineHeight: number; font: PDFFont; color: any },
    indent: number,
  ) {
    this.ensure(opts.lineHeight);
    this.page.drawText(line, {
      x: MARGIN + indent,
      y: this.y - opts.size,
      size: opts.size,
      font: opts.font,
      color: opts.color,
    });
    this.y -= opts.lineHeight;
  }

  private stampFooters() {
    const pages = this.doc.getPages();
    pages.forEach((p, i) => {
      const label = `Deep Research Agent · page ${i + 1} of ${pages.length}`;
      p.drawText(label, { x: MARGIN, y: MARGIN / 2, size: 8, font: this.font, color: gray(0.55) });
      p.drawText(new Date().toISOString().slice(0, 10), {
        x: PAGE_W - MARGIN - 52,
        y: MARGIN / 2,
        size: 8,
        font: this.font,
        color: gray(0.55),
      });
    });
  }
}

function gray(v: number) {
  return rgb(v, v, v);
}

export async function reportToPdf(report: Report): Promise<Uint8Array> {
  const flattened = [
    report.title,
    report.question,
    report.shortAnswer,
    report.confidenceReason,
    ...report.findings.flatMap((f) => [f.heading, ...f.bullets]),
    ...(report.conflicts ?? []),
    ...(report.uncertainties ?? []),
    ...report.sources.map((s) => `${s.title} ${s.url} ${s.supports ?? ''} ${s.quote ?? ''}`),
  ].join(' ');

  const ratio = latinRatio(flattened);
  if (ratio < 0.6) {
    throw new AppError(
      'UNSUPPORTED_TYPE',
      'This report contains characters (for example Bengali or Chinese script) that the built-in PDF font cannot render.',
      {
        status: 415,
        hint: 'Use "Download as Markdown", or open the print dialog and choose "Save as PDF" — your browser can render any script.',
      },
    );
  }

  const pdf = new Pdf();
  return pdf.build(report);
}

export function pdfFilename(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return `${slug || 'deep-research-report'}.pdf`;
}

function sanitizeFileName(title: string, ext: string): string {
  return pdfFilename(title).replace(/\.pdf$/, `.${ext}`);
}

export { sanitizeFileName };
